# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: hpc-libs tests
on:
  workflow_call:
  pull_request:

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: tox -e unit

  integration-test:
    name: Integration tests
    runs-on: ubuntu-latest
    needs:
      - inclusive-naming-check
      - lint
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Set up LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: 5.21/stable
      - name: Set up gambol
        run: |
          wget https://github.com/NucciTheBoss/gambol/releases/download/v0.1.0-rc2/gambol_0.1.0_amd64-rc2.snap
          sudo snap install ./gambol_*.snap --dangerous
          sudo snap connect gambol:lxd lxd:lxd
          sudo snap connect gambol:dot-gambol
      - name: Run tests
        run: tox -e integration
