# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: hpc-libs tests
on:
  workflow_call:
  pull_request:

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install tox
      - name: Run linters
        run: tox run -e lint

  typecheck:
    name: Static type checking
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install tox
      - name: Run tests
        run: tox run -e typecheck

  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install tox
      - name: Run tests
        run: tox run -e unit

  integration-test:
    name: Integration tests
    runs-on: ubuntu-24.04
    needs:
      - inclusive-naming-check
      - lint
      - typecheck
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pipx install tox
      - name: Set up LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: 5.21/stable
      - name: Set up gambol
        run: |
          sudo snap install gambol
      - name: Run tests
        run: tox run -e integration
