# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: hpc-libs tests
on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  inclusive-naming-check:
    name: Inclusive naming check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.39.0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.8
      - name: Run linters
        run: just lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.39.0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.8
      - name: Run unit tests
        run: just unit

  typecheck:
    name: Static type checking
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.39.0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.8
      - name: Run tests
        run: just typecheck

  integration-test:
    name: Integration tests
    runs-on: ubuntu-24.04
    needs:
      - inclusive-naming-check
      - lint
      - typecheck
      - unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.39.0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: 0.5.8
      - name: Set up LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: 5.21/stable
      - name: Set up gambol
        run: |
          sudo snap install gambol
      - name: Run tests
        run: just integration
